enum networksConstants {
    REQUEST_NETWORKS = '@@DASHBOARD/NETWORKS/REQUEST_NETWORKS',
    REQUEST_NETWORKS_SUCCESS = '@@DASHBOARD/NETWORKS/REQUEST_NETWORKS_SUCCESS',
    REQUEST_NETWORKS_ERROR = '@@DASHBOARD/NETWORKS/REQUEST_NETWORKS_ERROR',
    SELECT_NETWORK = '@@DASHBOARD/NETWORKS/SELECT_NETWORK',
}

export default networksConstants;