enum stationsConstants {
    REQUEST_STATIONS = '@@DASHBOARD/STATIONS/REQUEST_STATIONS',
    REQUEST_STATIONS_SUCCESS = '@@DASHBOARD/STATIONS/REQUEST_STATIONS_SUCCESS',
    REQUEST_STATIONS_ERROR = '@@DASHBOARD/STATIONS/REQUEST_STATIONS_ERROR',
    TOGGLE_STATION_LIKE = '@@DASHBOARD/STATIONS/TOGGLE_STATION_LIKE',
    TOGGLE_STATION_LIKE_SUCCESS = '@@DASHBOARD/STATIONS/TOGGLE_STATION_LIKE_SUCCESS',
}

export default stationsConstants;
